name: SONG_iodine
channels:
  - conda-forge
dependencies:
  - python=3.10
  - astropy=4.2.1
  - h5py=2.10.0
  - numpy=1.20.1
  - lmfit=1.0.2
  - pathos=0.2.8
  - matplotlib=3.3.4
  - progressbar2=3.37.1
  - dill=0.3.4
  - pip
  - pip:
      - barycorrpy==0.4.4
